# Generated by Django 5.2.5 on 2025-08-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='FactComment',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='FactLike',
        ),
    ]
