# Generated by Django 5.2.5 on 2025-09-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comentario_autor_alter_comentario_post'),
        ('heroes', '0004_hero_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.hero'),
        ),
    ]
