# Generated by Django 5.2.5 on 2025-08-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('history', models.TextField(blank=True, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
