# Generated by Django 5.2.5 on 2025-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_hero_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='imagem',
            field=models.ImageField(blank=True, default='fotos_herois/default_profile.png', null=True, upload_to='fotos_herois/'),
        ),
    ]