# Generated by Django 5.2.5 on 2025-10-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_alter_hero_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hero',
            name='codinome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
